// ════════════════════════════════════════════════════════════════════════════
// yara-rules-coverage.spec.ts — Per-rule coverage regression net.
//
// Reads `yara-rules-fired.json` (regenerated by
// `scripts/gen_yara_coverage.py`) and asserts that every (anchor,
// rule) pair the corpus once produced still produces those rules.
//
// Why this exists alongside `snapshot-matrix.spec.ts`:
//
//   The matrix pins at most three "family-anchor" rules per fixture
//   (intentional — pinning the long tail invites churn). That leaves
//   ~50 rules across the corpus that *do* fire but aren't pinned by
//   the matrix and could silently stop firing. This spec closes the
//   gap by inverting the relationship: for every rule, load its
//   first-anchor fixture and confirm the rule appears in the rule
//   set.
//
// Why ONE Playwright test that walks all anchors?
//   Same rationale as `snapshot-matrix.spec.ts` — see that file's
//   header. Each anchor runs as a `test.step` with `expect.soft`, so
//   per-anchor diagnostic granularity survives while the per-test
//   bookkeeping overhead collapses into one runner cycle.
//
// Unanchored rules are documentation only — see
// `yara-rules-fired.json:unanchoredRules`. CI does NOT block on
// growing that list (the corpus is a living document).
// ════════════════════════════════════════════════════════════════════════════

import * as fs from 'fs';
import * as path from 'path';
import { test, expect } from '@playwright/test';
import {
  REPO_ROOT,
  loadFixture,
  ruleNames,
  useSharedBundlePage,
} from '../helpers/playwright-helpers';

interface CoverageManifest {
  summary: {
    totalRulesDefined: number;
    rulesFiredInCorpus: number;
    rulesUnanchored: number;
    anchorFixtures: number;
  };
  anchorFixtures: Record<string, string[]>;
  unanchoredRules: string[];
}

function loadManifest(): CoverageManifest {
  const p = path.join(REPO_ROOT, 'tests', 'e2e-fixtures', 'yara-rules-fired.json');
  if (!fs.existsSync(p)) {
    throw new Error(
      `${p} missing — regenerate with python scripts/gen_yara_coverage.py`);
  }
  return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

const MANIFEST = loadManifest();
const ANCHOR_ENTRIES = Object.entries(MANIFEST.anchorFixtures);

test.describe('YARA rule coverage (per-anchor)', () => {
  const ctx = useSharedBundlePage();

  // Single test. Each anchor runs as a `test.step`, asserting the
  // full subset of "rules anchored here" via `expect.soft` so a
  // regression in one rule doesn't mask regressions in others.
  test(`walks ${ANCHOR_ENTRIES.length} anchor fixtures`, async () => {
    test.setTimeout(10 * 60 * 1000); // 10 min wall budget for the full walk

    for (const [anchor, rules] of ANCHOR_ENTRIES) {
      await test.step(`${anchor} (${rules.length} rules)`, async () => {
        const findings = await loadFixture(ctx.page, anchor);
        const seen = ruleNames(findings);
        const missing: string[] = [];
        for (const r of rules) {
          if (!seen.includes(r)) missing.push(r);
        }
        expect.soft(
          missing,
          `${anchor}: rules expected to fire but didn't: ${missing.join(', ')}`,
        ).toEqual([]);
      });
    }
  });

  // Stand-alone documentation test that exposes the coverage summary
  // in the test log. Always passes — it's purely informational.
  test('YARA rule coverage summary (informational)', () => {
    const s = MANIFEST.summary;
    console.log(
      `[yara-coverage] defined=${s.totalRulesDefined} `
      + `fired=${s.rulesFiredInCorpus} `
      + `unanchored=${s.rulesUnanchored} `
      + `anchors=${s.anchorFixtures}`);
    // Sanity: at least 30% of defined rules must have fixture
    // coverage. Below that we've either shipped a rules-pack regression
    // or the corpus has decayed — either way, manual investigation.
    const pct = MANIFEST.summary.rulesFiredInCorpus
      / Math.max(1, MANIFEST.summary.totalRulesDefined);
    expect(pct).toBeGreaterThan(0.30);
  });
});
