#!/usr/bin/env python3
"""run_fuzz.py — orchestrator for Loupe's fuzz harness.

Loupe's fuzz rig is opt-in (mirrors `scripts/run_perf.py`). The default
`python make.py` and `python make.py test` paths NEVER trigger fuzzing.
You invoke this script (or `python make.py fuzz`) explicitly when you
want to fuzz one or more targets.

Two execution modes:

  1. Coverage-guided fuzzing under Jazzer.js (`@jazzer.js/core`). Loupe
     ships no committed `package.json`, so the script provisions
     `@jazzer.js/core` ephemerally into `dist/test-deps/` (the same dir
     `run_tests_e2e.py` uses). `JAZZER_VERSION` below is the single
     source of truth for the pin.

  2. Replay mode (`--replay`) — drive each target through its seed
     corpus + a deterministic byte-mutator that ships with the harness
     itself (no npm dependencies). Used for:
       • smoke-testing a new target without `npm install`
       • CI-equivalent quick checks (--quick → 5s/target)
       • reproducing a known crash (`--reproduce <path-to-crash>`)

Outputs:
  dist/fuzz-corpus/<target>/      libFuzzer-format growing corpus (Jazzer.js owns)
  dist/fuzz-crashes/<target>/<sha>/{input.bin,stack.txt,minimised.bin}
  dist/fuzz-coverage/summary.md   per-target coverage + iteration counts

Usage:
  python scripts/run_fuzz.py                          # all targets, 60 s each
  python scripts/run_fuzz.py text/ioc-extract         # single target
  python scripts/run_fuzz.py --time 300               # 5 min per target
  python scripts/run_fuzz.py --quick                  # 5 s/target smoke
  python scripts/run_fuzz.py --replay                 # no Jazzer.js, deterministic
  python scripts/run_fuzz.py --reproduce dist/fuzz-crashes/X/Y/input.bin
  python scripts/run_fuzz.py --list                   # list discovered targets
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import shutil
import subprocess
import sys
import time

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FUZZ_DIR = os.path.join(BASE, 'tests', 'fuzz')
TARGETS_DIR = os.path.join(FUZZ_DIR, 'targets')
DIST_DIR = os.path.join(BASE, 'dist')
DEPS_DIR = os.path.join(DIST_DIR, 'test-deps')
DEPS_NODE_MODULES = os.path.join(DEPS_DIR, 'node_modules')
DEPS_PACKAGE_JSON = os.path.join(DEPS_DIR, 'package.json')
INSTALL_MARKER = os.path.join(DEPS_DIR, '.installed-fuzz-version')
CORPUS_DIR = os.path.join(DIST_DIR, 'fuzz-corpus')
CRASHES_DIR = os.path.join(DIST_DIR, 'fuzz-crashes')
COVERAGE_DIR = os.path.join(DIST_DIR, 'fuzz-coverage')

# ── Pinned Jazzer.js version ──────────────────────────────────────────────────
# Single source of truth for the fuzzing engine. Bump deliberately via
# PR — the bump is visible in this constant, the cached node_modules
# is rebuilt next run, and no committed package.json contradicts the
# pin. License: Apache-2.0 (verified at pin-bump time).
JAZZER_VERSION = '4.0.0'

# Reuse Playwright's package.json key to avoid double-installing
# (`run_tests_e2e.py` and this script share `dist/test-deps/`).
PLAYWRIGHT_VERSION_FALLBACK = '1.56.0'  # only used if e2e script not yet run


def _die(msg: str, code: int = 2) -> None:
    print(f'ERROR  {msg}', file=sys.stderr)
    sys.exit(code)


def _need(cmd: str) -> str:
    found = shutil.which(cmd)
    if not found:
        _die(f'`{cmd}` not on PATH. Loupe fuzz tests require Node ≥ 20 + npm.')
    return found


def _read_pinned_playwright_version() -> str:
    """Pull the Playwright pin from run_tests_e2e.py so we can install
    both deps in a single npm pass without contradicting the e2e script."""
    e2e = os.path.join(BASE, 'scripts', 'run_tests_e2e.py')
    try:
        with open(e2e, 'r', encoding='utf-8') as f:
            for line in f:
                if line.startswith('PLAYWRIGHT_VERSION'):
                    # PLAYWRIGHT_VERSION = '1.56.0'
                    return line.split("'")[1]
    except OSError:
        pass
    return PLAYWRIGHT_VERSION_FALLBACK


def _build_package_json() -> dict:
    return {
        'name': 'loupe-test-deps',
        'private': True,
        'version': '0.0.0',
        'description': 'Auto-generated by scripts/run_tests_e2e.py + run_fuzz.py. Do not commit.',
        'dependencies': {
            '@playwright/test': _read_pinned_playwright_version(),
            '@jazzer.js/core': JAZZER_VERSION,
        },
    }


def _ensure_jazzer_install() -> None:
    """Install @jazzer.js/core into dist/test-deps/. Idempotent — marker
    file avoids re-running npm on warm invocations."""
    os.makedirs(DEPS_DIR, exist_ok=True)
    pkg = _build_package_json()
    # Always rewrite package.json so the version pin in this script wins
    # over any stale on-disk copy.
    with open(DEPS_PACKAGE_JSON, 'w', encoding='utf-8') as f:
        json.dump(pkg, f, indent=2, sort_keys=True)
        f.write('\n')

    marker_target = f'jazzer={JAZZER_VERSION}'
    jazzer_dir = os.path.join(DEPS_NODE_MODULES, '@jazzer.js', 'core')
    if (os.path.isdir(jazzer_dir)
            and os.path.isfile(INSTALL_MARKER)):
        with open(INSTALL_MARKER, 'r', encoding='utf-8') as f:
            if f.read().strip() == marker_target:
                return  # Already up to date.

    npm = _need('npm')
    print(f'$ {npm} install --prefix {os.path.relpath(DEPS_DIR, BASE)}  '
          f'(jazzer.js@{JAZZER_VERSION}; ~30 s on first run)', flush=True)
    rc = subprocess.call(
        [npm, 'install', '--prefix', DEPS_DIR,
         '--no-audit', '--no-fund', '--silent'],
        cwd=BASE,
    )
    if rc != 0:
        _die(f'npm install failed with exit code {rc}', code=rc)
    with open(INSTALL_MARKER, 'w', encoding='utf-8') as f:
        f.write(marker_target + '\n')


def _discover_targets() -> list[str]:
    """Return sorted list of target identifiers (e.g. 'text/ioc-extract')."""
    out = []
    pattern = os.path.join(TARGETS_DIR, '**', '*.fuzz.js')
    for p in sorted(glob.glob(pattern, recursive=True)):
        rel = os.path.relpath(p, TARGETS_DIR)
        rel = rel[:-len('.fuzz.js')]  # strip suffix
        # Normalise separators for Windows (we display as forward-slash).
        rel = rel.replace(os.sep, '/')
        out.append(rel)
    return out


def _resolve_target(name: str) -> str:
    """Map a user-supplied target name to its absolute .fuzz.js path."""
    cand = name.replace(os.sep, '/').replace('.fuzz.js', '')
    abs_path = os.path.join(TARGETS_DIR, *cand.split('/')) + '.fuzz.js'
    if os.path.isfile(abs_path):
        return abs_path
    # Try as suffix match (e.g. user typed 'ioc-extract' for 'text/ioc-extract').
    matches = [t for t in _discover_targets() if t.endswith('/' + cand) or t == cand]
    if len(matches) == 1:
        return os.path.join(TARGETS_DIR, *matches[0].split('/')) + '.fuzz.js'
    if not matches:
        _die(f'no fuzz target matches {name!r}. Use --list to see available targets.')
    _die(f'ambiguous target name {name!r} — matches: {", ".join(matches)}')


def _ensure_dist_dirs(target_id: str) -> tuple[str, str]:
    """Create per-target corpus + crash dirs; return their paths."""
    corpus = os.path.join(CORPUS_DIR, target_id)
    crashes = os.path.join(CRASHES_DIR, target_id)
    os.makedirs(corpus, exist_ok=True)
    os.makedirs(crashes, exist_ok=True)
    os.makedirs(COVERAGE_DIR, exist_ok=True)
    return corpus, crashes


def _coverage_dir_for(target_id: str) -> str:
    """Per-target subdirectory under dist/fuzz-coverage/v8/ for V8's
    NODE_V8_COVERAGE dumps + the harness's manifest sidecar. Cleaned
    fresh at the start of each --coverage run so stale per-process
    JSON from a previous invocation can't pollute the next aggregation
    pass."""
    return os.path.join(COVERAGE_DIR, 'v8', *target_id.split('/'))


def _prepare_coverage_dir(target_id: str) -> str:
    d = _coverage_dir_for(target_id)
    if os.path.isdir(d):
        # Fresh slate per run: the V8 dump + manifest filenames are
        # process-pid suffixed and would otherwise accumulate across
        # invocations until they hit the filesystem.
        for entry in os.listdir(d):
            full = os.path.join(d, entry)
            try:
                if os.path.isdir(full):
                    shutil.rmtree(full)
                else:
                    os.remove(full)
            except OSError:
                pass
    os.makedirs(d, exist_ok=True)
    return d


def _augment_env_for_coverage(env: dict, target_id: str) -> None:
    """Add NODE_V8_COVERAGE + harness env vars in-place."""
    cov = _prepare_coverage_dir(target_id)
    env['NODE_V8_COVERAGE'] = cov
    env['LOUPE_FUZZ_COVERAGE_DIR'] = cov
    env['LOUPE_FUZZ_TARGET_ID'] = target_id


def _run_replay(target_path: str, target_id: str, args) -> int:
    """Drive the target through its declared seeds + the deterministic
    byte-mutator in tests/fuzz/helpers/harness.js. No npm install
    required — runs entirely off Node + Loupe source."""
    runner = os.path.join(FUZZ_DIR, 'helpers', 'replay-runner.js')
    if not os.path.isfile(runner):
        _die(f'expected replay runner at {runner}')
    node = _need('node')
    cmd = [node, runner, target_path]
    if args.iterations:
        cmd += ['--iterations', str(args.iterations)]
    if args.quick:
        cmd += ['--quick']
    if args.continue_on_error:
        cmd += ['--continue-on-error']
    if args.reproduce:
        cmd += ['--reproduce', args.reproduce]
    env = os.environ.copy()
    if args.coverage:
        _augment_env_for_coverage(env, target_id)
    print(f'$ {" ".join(cmd)}', flush=True)
    return subprocess.call(cmd, cwd=BASE, env=env)


def _run_jazzer(target_path: str, target_id: str, args) -> int:
    """Drive the target under Jazzer.js libFuzzer."""
    _ensure_jazzer_install()
    corpus, crashes = _ensure_dist_dirs(target_id)
    node = _need('node')

    # Pinned wall-clock budget per target. The DEFAULT_PER_ITER_BUDGET_MS
    # in harness.js (2 500 ms) caps any single iteration; --time below
    # caps the total wall-clock per target.
    total_seconds = 5 if args.quick else (args.time or 60)

    # Jazzer.js exposes `startFuzzingAsync({ … })` from its public API.
    # We invoke it via a tiny bootstrap so the target file itself stays
    # bare-bones (just a `module.exports.fuzz = …`).
    bootstrap = os.path.join(FUZZ_DIR, 'helpers', 'jazzer-bootstrap.js')
    if not os.path.isfile(bootstrap):
        _die(f'expected jazzer bootstrap at {bootstrap}')

    env = os.environ.copy()
    existing = env.get('NODE_PATH')
    env['NODE_PATH'] = (
        DEPS_NODE_MODULES if not existing
        else f'{DEPS_NODE_MODULES}{os.pathsep}{existing}'
    )
    env['LOUPE_FUZZ_TARGET'] = target_path
    env['LOUPE_FUZZ_TARGET_ID'] = target_id
    env['LOUPE_FUZZ_CORPUS'] = corpus
    env['LOUPE_FUZZ_CRASHES'] = crashes
    env['LOUPE_FUZZ_TIME'] = str(total_seconds)
    if args.coverage:
        # Note: NODE_V8_COVERAGE applies to the orchestrating Node process.
        # Jazzer.js's libFuzzer wrapper drives many fuzz iterations within
        # ONE Node process, so a single coverage dump captures aggregate
        # coverage for the whole run — exactly what we want.
        _augment_env_for_coverage(env, target_id)

    cmd = [node, bootstrap]
    print(f'$ {" ".join(cmd)}  '
          f'# target={target_id} time={total_seconds}s '
          f'corpus={os.path.relpath(corpus, BASE)}', flush=True)
    rc = subprocess.call(cmd, cwd=BASE, env=env)
    return rc


def _list_targets() -> int:
    targets = _discover_targets()
    if not targets:
        print('(no fuzz targets discovered under tests/fuzz/targets/)')
        return 0
    print(f'{len(targets)} fuzz target(s):')
    for t in targets:
        print(f'  {t}')
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog='run_fuzz.py',
        description='Loupe fuzz harness orchestrator (opt-in, local-only).',
    )
    parser.add_argument('targets', nargs='*',
                        help='target identifiers (e.g. text/ioc-extract). '
                             'Default: all discovered targets.')
    parser.add_argument('--time', type=int, default=None,
                        help='wall-clock seconds per target under Jazzer.js (default 60).')
    parser.add_argument('--quick', action='store_true',
                        help='5 s/target smoke (overrides --time).')
    parser.add_argument('--replay', action='store_true',
                        help='use the deterministic replay mutator (no Jazzer.js).')
    parser.add_argument('--iterations', type=int, default=None,
                        help='replay iterations per seed (default 200).')
    parser.add_argument('--continue-on-error', action='store_true',
                        help='replay: keep going past first failure.')
    parser.add_argument('--reproduce', type=str, default=None,
                        help='replay one specific input file against a target.')
    parser.add_argument('--list', action='store_true',
                        help='list discovered targets and exit.')
    parser.add_argument('--coverage', action='store_true',
                        help='record V8 source coverage per target and emit a '
                             'per-src/file line-coverage table in '
                             'dist/fuzz-coverage/summary.md. Adds a few percent '
                             'wall-clock overhead and ~1 MiB of dist/ output '
                             'per target.')
    args = parser.parse_args()

    if args.list:
        return _list_targets()

    targets = _discover_targets()
    if not targets:
        print('No fuzz targets discovered under tests/fuzz/targets/. '
              'Add a *.fuzz.js file (see tests/fuzz/README.md).')
        return 0

    selected = []
    if args.targets:
        for name in args.targets:
            selected.append((_resolve_target(name),
                             name.replace(os.sep, '/').replace('.fuzz.js', '')))
    else:
        for tid in targets:
            selected.append((os.path.join(TARGETS_DIR, *tid.split('/')) + '.fuzz.js',
                             tid))

    print(f'Loupe fuzz — running {len(selected)} target(s) '
          f'in {"replay" if args.replay or args.reproduce else "jazzer"} mode')

    overall_rc = 0
    summary = []
    t_start = time.perf_counter()
    for target_path, target_id in selected:
        banner = f' fuzz: {target_id} '.center(60, '─')
        print(f'\n{banner}')
        t0 = time.perf_counter()
        if args.replay or args.reproduce:
            rc = _run_replay(target_path, target_id, args)
        else:
            rc = _run_jazzer(target_path, target_id, args)
        dt = time.perf_counter() - t0
        status = 'OK' if rc == 0 else f'FAIL ({rc})'
        print(f'[{status}] {target_id} — {dt:.2f}s')
        summary.append({'target': target_id, 'rc': rc, 'seconds': dt})
        if rc != 0:
            overall_rc = rc
            # Don't bail — fuzz a different target may still find bugs.

    dt_total = time.perf_counter() - t_start
    os.makedirs(COVERAGE_DIR, exist_ok=True)
    with open(os.path.join(COVERAGE_DIR, 'summary.json'), 'w', encoding='utf-8') as f:
        json.dump({'targets': summary, 'totalSeconds': dt_total}, f, indent=2)
    md = os.path.join(COVERAGE_DIR, 'summary.md')
    with open(md, 'w', encoding='utf-8') as f:
        f.write('# Fuzz run summary\n\n')
        f.write(f'Total wall-clock: {dt_total:.1f}s across {len(summary)} target(s).\n\n')
        f.write('| target | rc | seconds |\n|---|---:|---:|\n')
        for s in summary:
            f.write(f'| {s["target"]} | {s["rc"]} | {s["seconds"]:.1f} |\n')

        if args.coverage:
            # Lazy-import the aggregator only when the flag is set — keeps
            # the default-path import surface minimal.
            from fuzz_coverage_aggregate import aggregate_and_render
            try:
                cov_section = aggregate_and_render(
                    coverage_dir=os.path.join(COVERAGE_DIR, 'v8'),
                    repo_root=BASE,
                    target_ids=[s['target'] for s in summary],
                )
                f.write('\n')
                f.write(cov_section)
            except Exception as exc:
                # Aggregation is opportunistic; don't poison the run on
                # a parse error.
                f.write(f'\n## Coverage\n\n_aggregation failed: {exc}_\n')
                print(f'WARN  coverage aggregation failed: {exc}', file=sys.stderr)
    print(f'\nWrote {os.path.relpath(md, BASE)}')
    print(f'OK    fuzz pipeline finished in {dt_total:.2f}s '
          f'(rc={overall_rc})')
    return overall_rc


if __name__ == '__main__':
    sys.exit(main())
