#!/usr/bin/env python3
"""run_tests_e2e.py — execute Playwright over tests/e2e-fixtures/ + tests/e2e-ui/.

Loupe deliberately ships without a committed `package.json` / lockfile
(see CONTRIBUTING.md § Determinism). The test pipeline still needs
`@playwright/test` resolvable from the test file imports, so this script
provisions an EPHEMERAL local install under `dist/test-deps/` (which is
gitignored). The version pinned in `PLAYWRIGHT_VERSION` is the single
source of truth — bump it deliberately via PR; CI must use the same pin.

Workflow:
  1. Verify `docs/index.test.html` exists (run `python make.py test-build`
     first, otherwise this fails fast with a clear error).
  2. Generate `dist/test-deps/package.json` from the pinned version.
  3. Run `npm install --prefix dist/test-deps` if `node_modules` is
     missing or the install marker doesn't match the pin (cheap, idempotent).
  4. Run `dist/test-deps/node_modules/.bin/playwright test --config
     tests/playwright.config.ts`. NODE_PATH includes the staged
     `node_modules` so the test files' `import '@playwright/test'`
     resolves without us having to vendor the package.
  5. Run `playwright install --with-deps chromium` once on first use so
     the bundled Chromium is available. Tracked via marker file so
     repeated runs skip this expensive step.

The whole `dist/test-deps/` tree is disposable — `rm -rf dist/test-deps`
forces a clean re-install on next run.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEST_BUNDLE = os.path.join(BASE, 'docs', 'index.test.html')

# ── Pinned Playwright Test version ────────────────────────────────────────────
# Single source of truth. Bump deliberately via PR; CI must use the same
# pin. Same convention as `eslint@9.39.4` in `.github/workflows/ci.yml`.
# We pull `@playwright/test` (the test runner) — NOT `playwright` (the
# browser driver alone) — because the test files import `defineConfig`,
# `test`, and `expect` from `@playwright/test`.
PLAYWRIGHT_VERSION = '1.56.0'

# ── Ephemeral install location ────────────────────────────────────────────────
# Under `dist/` so it's covered by the existing `.gitignore` rule for
# build artefacts. A separate subdirectory keeps it from colliding with
# the release SBOM / signed-bundle outputs that also land in `dist/`.
DEPS_DIR = os.path.join(BASE, 'dist', 'test-deps')
DEPS_NODE_MODULES = os.path.join(DEPS_DIR, 'node_modules')
DEPS_PACKAGE_JSON = os.path.join(DEPS_DIR, 'package.json')
INSTALL_MARKER = os.path.join(DEPS_DIR, '.installed-version')
BROWSERS_MARKER = os.path.join(DEPS_DIR, '.browsers-installed')

PACKAGE_JSON = {
    'name': 'loupe-test-deps',
    'private': True,
    'version': '0.0.0',
    'description': 'Auto-generated by scripts/run_tests_e2e.py. Do not commit.',
    'dependencies': {
        '@playwright/test': PLAYWRIGHT_VERSION,
    },
}


def _die(msg: str, code: int = 2) -> None:
    print(f'ERROR  {msg}', file=sys.stderr)
    sys.exit(code)


def _need(cmd: str) -> str:
    found = shutil.which(cmd)
    if not found:
        _die(f'`{cmd}` not on PATH. Loupe e2e tests require Node ≥ 20 + npm.')
    return found


def _ensure_install() -> None:
    """Ensure `dist/test-deps/node_modules/@playwright/test` matches
    `PLAYWRIGHT_VERSION`. Re-runs `npm install` only when the marker is
    stale — cheap on warm runs (~10 ms)."""
    os.makedirs(DEPS_DIR, exist_ok=True)
    # Always rewrite package.json so the version pin in this script wins
    # over any stale on-disk copy.
    with open(DEPS_PACKAGE_JSON, 'w', encoding='utf-8') as f:
        json.dump(PACKAGE_JSON, f, indent=2, sort_keys=True)
        f.write('\n')

    if (os.path.isdir(DEPS_NODE_MODULES)
            and os.path.isfile(INSTALL_MARKER)):
        with open(INSTALL_MARKER, 'r', encoding='utf-8') as f:
            if f.read().strip() == PLAYWRIGHT_VERSION:
                return  # Already up to date.

    npm = _need('npm')
    print(f'$ {npm} install --prefix {os.path.relpath(DEPS_DIR, BASE)} '
          '(this may take ~30 s on first run)', flush=True)
    rc = subprocess.call(
        [npm, 'install', '--prefix', DEPS_DIR,
         '--no-audit', '--no-fund', '--silent'],
        cwd=BASE,
    )
    if rc != 0:
        _die(f'npm install failed with exit code {rc}', code=rc)
    with open(INSTALL_MARKER, 'w', encoding='utf-8') as f:
        f.write(PLAYWRIGHT_VERSION + '\n')


def _ensure_browsers() -> None:
    """Run `playwright install --with-deps chromium` once. Marker file
    avoids the multi-second startup of the install command on warm runs."""
    if os.path.isfile(BROWSERS_MARKER):
        return
    pw_cli = os.path.join(DEPS_NODE_MODULES, '.bin', 'playwright')
    if not os.path.isfile(pw_cli):
        _die(f'expected playwright CLI at {pw_cli} after npm install')
    print(f'$ {os.path.relpath(pw_cli, BASE)} install chromium '
          '(first-time browser download)', flush=True)
    # `--with-deps` is Linux-only and may need sudo. We skip it here and
    # let the user opt in via `PWBROWSER_DEPS=1` if they want it; CI
    # provisions the system deps via apt before running this script.
    args = [pw_cli, 'install', 'chromium']
    if os.environ.get('PWBROWSER_DEPS'):
        args.insert(2, '--with-deps')
    rc = subprocess.call(args, cwd=BASE)
    if rc != 0:
        _die(f'playwright install failed with exit code {rc}', code=rc)
    with open(BROWSERS_MARKER, 'w', encoding='utf-8') as f:
        f.write(PLAYWRIGHT_VERSION + '\n')


def main() -> int:
    if not os.path.isfile(TEST_BUNDLE):
        _die(
            f'docs/index.test.html not found at {TEST_BUNDLE}.\n'
            '       Run `python make.py test-build` first (or `python '
            'scripts/build.py --test-api`).',
        )

    _need('node')
    _ensure_install()
    _ensure_browsers()

    pw_cli = os.path.join(DEPS_NODE_MODULES, '.bin', 'playwright')
    cfg = os.path.join(BASE, 'tests', 'playwright.config.ts')
    cmd = [pw_cli, 'test', '--config', cfg] + sys.argv[1:]

    # Make `@playwright/test` resolvable from the test files. The test
    # files live outside `dist/test-deps/` so Node's normal upward
    # `node_modules` walk doesn't find the install — we point NODE_PATH
    # at it explicitly. This is the standard escape hatch Node offers
    # for exactly this layout.
    env = os.environ.copy()
    existing = env.get('NODE_PATH')
    env['NODE_PATH'] = (
        DEPS_NODE_MODULES if not existing
        else f'{DEPS_NODE_MODULES}{os.pathsep}{existing}'
    )

    print(f'$ {" ".join(cmd)}', flush=True)
    return subprocess.call(cmd, cwd=BASE, env=env)


if __name__ == '__main__':
    sys.exit(main())
