'use strict';
// csv-parser.test.js — RFC-4180 state-machine parser shared by the CSV
// renderer, the timeline worker, and the timeline main-thread fallback.
//
// The bug this test guards against: prior to the parser refactor, all
// three CSV/TSV pipelines split the buffer on `\n` *before* parsing
// quotes. A `\n` inside a `"..."` quoted cell terminated the row
// prematurely and the rest of the cell value bled into a fresh row at
// column 0. Files generated by joining sources with embedded multi-line
// strings (logs, JSON-blob columns, exported tickets) lost almost all
// their structure as a result.
//
// CsvRenderer.parseChunk is now a quote-aware state machine: a quoted
// cell may contain literal `\n`, the delimiter, and `""`-escaped
// quotes. State threads across calls so a chunked decoder feeding the
// parser one decoded slice at a time produces the same rows as a
// single-shot parse of the full buffer.
//
// Tests cover: plain unquoted, embedded newlines, embedded delimiters,
// `""` escapes, ragged rows, unterminated quote at EOF, CRLF inside
// quotes, chunk boundary mid-quoted-cell, header sniff with quoted
// commas, and short-row padding via the renderer wrapper.

const test = require('node:test');
const assert = require('node:assert/strict');
const { loadModules, host } = require('../helpers/load-bundle.js');

// csv-renderer.js references RENDER_LIMITS (constants.js) and the
// IOC.PATTERN constant + escalateRisk helper. None of those code paths
// fire from the parser tests below, but we load constants.js so
// instantiating CsvRenderer at module-eval time succeeds.
const ctx = loadModules(
  ['src/constants.js', 'src/renderers/csv-renderer.js'],
  { expose: ['CsvRenderer', 'IOC', 'RENDER_LIMITS'] },
);
const { CsvRenderer } = ctx;

// Convenience: fully parse `text` with `delim` in one shot, using the
// shared state-machine API. Returns just the rows (most tests don't
// care about offsets).
function parseAll(text, delim) {
  const state = CsvRenderer.initParserState();
  const result = CsvRenderer.parseChunk(text, 0, state, delim, {
    baseOffset: 0, maxRows: 0, flush: true,
  });
  return host(result.rows);
}

// Fetch rows + endedInQuotes flag — for tests that assert the
// malformed-row sentinel surfaces correctly on truncated quotes.
function parseAllWithFlag(text, delim) {
  const state = CsvRenderer.initParserState();
  const result = CsvRenderer.parseChunk(text, 0, state, delim, {
    baseOffset: 0, maxRows: 0, flush: true,
  });
  return { rows: host(result.rows), endedInQuotes: result.endedInQuotes };
}

// ── Plain unquoted ─────────────────────────────────────────────────────

test('csv-parser: plain unquoted rows split on the delimiter', () => {
  // The fast path (no `"` between row start and the next `\n`) uses
  // native String.split; this test pins its output to the same rows
  // the slow path would produce.
  const text = 'a,b,c\n1,2,3\n4,5,6\n';
  assert.deepEqual(parseAll(text, ','), [
    ['a', 'b', 'c'],
    ['1', '2', '3'],
    ['4', '5', '6'],
  ]);
});

test('csv-parser: TSV delimiter works the same as CSV', () => {
  const text = 'a\tb\tc\n1\t2\t3\n';
  assert.deepEqual(parseAll(text, '\t'), [
    ['a', 'b', 'c'],
    ['1', '2', '3'],
  ]);
});

test('csv-parser: trailing line with no \\n is emitted on flush', () => {
  // Many real-world CSVs end without a final newline. The parser's
  // `flush:true` final call must still emit that row.
  assert.deepEqual(parseAll('a,b,c\n1,2,3', ','), [
    ['a', 'b', 'c'],
    ['1', '2', '3'],
  ]);
});

test('csv-parser: blank physical lines are skipped', () => {
  // Backward-compat with the legacy line-oriented parser, which used
  // `if (lineEnd > offset)` to skip zero-length lines. A row of one
  // empty cell would be a confusing artefact.
  assert.deepEqual(parseAll('a,b\n\n\n1,2\n', ','), [
    ['a', 'b'],
    ['1', '2'],
  ]);
});

// ── Quoted cells ───────────────────────────────────────────────────────

test('csv-parser: quoted cell with embedded newline stays in one row', () => {
  // The exact symptom the user reported: a "..." cell containing a
  // literal `\n` was splitting the row at the newline and pushing the
  // continuation into column 0 of a phantom next row.
  const text = 'h1,h2,h3\n"line one\nline two",b,c\nx,y,z\n';
  assert.deepEqual(parseAll(text, ','), [
    ['h1', 'h2', 'h3'],
    ['line one\nline two', 'b', 'c'],
    ['x', 'y', 'z'],
  ]);
});

test('csv-parser: quoted cell with embedded delimiter stays in one cell', () => {
  // The "the comma is data, not a separator" case.
  const text = 'a,b,c\n"x,y,z",2,3\n';
  assert.deepEqual(parseAll(text, ','), [
    ['a', 'b', 'c'],
    ['x,y,z', '2', '3'],
  ]);
});

test('csv-parser: doubled quotes inside a quoted cell escape to one quote', () => {
  // RFC-4180 escape: `""` inside `"..."` is a literal `"`. Many
  // spreadsheets emit this when a cell value contains a quote.
  const text = 'a,b\n"He said ""hi""",2\n';
  assert.deepEqual(parseAll(text, ','), [
    ['a', 'b'],
    ['He said "hi"', '2'],
  ]);
});

test('csv-parser: quoted cell with newline AND delimiter stays one cell', () => {
  // The combined case — both kinds of quote-protected literal in the
  // same cell. This is what JSON-blob columns in CSV look like.
  const text = 'h\n"line1,still line1\nline2",ok\n';
  assert.deepEqual(parseAll(text, ','), [
    ['h'],
    ['line1,still line1\nline2', 'ok'],
  ]);
});

// ── User's case: ragged rows + multi-line quoted cells ────────────────

test('csv-parser: 13-col header, 7-col bodies with multi-line quoted cells', () => {
  // Reconstructs the user's reported file shape: 28 physical lines,
  // 4 logical rows (1 header + 3 bodies), 13-col header, body rows
  // with ~7 cols, some cells contain multi-line quoted data. The
  // parser must produce exactly 4 logical rows.
  const text =
    'a\tb\tc\td\te\tf\tg\th\ti\tj\tk\tl\tm\n' +                 // 13 cols
    'r1c1\tr1c2\t"line A\nline B\nline C"\tr1c4\tr1c5\tr1c6\tr1c7\n' + // 7 cols, multi-line cell
    'r2c1\tr2c2\t"single line"\t"another\nmulti\nline\nblock"\tr2c5\tr2c6\tr2c7\n' + // 7 cols
    'r3c1\tr3c2\tr3c3\tr3c4\tr3c5\tr3c6\t"final\nrow\nspans\nlines"\n';            // 7 cols
  const rows = parseAll(text, '\t');
  assert.equal(rows.length, 4, 'expected exactly 4 logical rows');
  assert.equal(rows[0].length, 13);
  assert.equal(rows[1].length, 7);
  assert.equal(rows[2].length, 7);
  assert.equal(rows[3].length, 7);
  assert.ok(rows[1][2].includes('\n'),    'row 1 col 2 should contain literal \\n');
  assert.equal(rows[1][2], 'line A\nline B\nline C');
  assert.equal(rows[2][3], 'another\nmulti\nline\nblock');
  assert.equal(rows[3][6], 'final\nrow\nspans\nlines');
});

// ── Malformed input ────────────────────────────────────────────────────

test('csv-parser: unterminated quote at EOF emits one final row, sets endedInQuotes', () => {
  // The parser must not loop or throw on an unclosed `"`. It should
  // emit whatever it ate as the last row and surface
  // `endedInQuotes:true` so the renderer can flag that single row as
  // malformed.
  const text = 'a,b\n"started but never closed,more,more\n';
  const { rows, endedInQuotes } = parseAllWithFlag(text, ',');
  assert.equal(endedInQuotes, true,  'endedInQuotes flag must be set');
  assert.equal(rows.length, 2,       'header + one swallowed body row');
  // The unterminated cell ate everything from its opening `"` to EOF.
  assert.ok(rows[1][0].includes('started but never closed'));
  assert.ok(rows[1][0].includes('more'));
});

// ── CRLF inside quotes ─────────────────────────────────────────────────

test('csv-parser: CRLF inside a quoted cell is preserved as the cell content', () => {
  // The renderer normalises CRLF→LF *outside* the parser; by the time
  // text reaches parseChunk, all line endings are LF. This test pins
  // that contract: feeding LF-only text in produces LF-only cell
  // content out, even when the LF is inside a quoted cell.
  const text = 'h\n"a\nb",ok\n';
  assert.deepEqual(parseAll(text, ','), [
    ['h'],
    ['a\nb', 'ok'],
  ]);
});

// ── Chunked / streaming ────────────────────────────────────────────────

test('csv-parser: chunk boundary mid-quoted-cell does not split the row', () => {
  // The worker decodes in 16 MB UTF-8 chunks and feeds the parser one
  // chunk at a time. If a multi-line quoted cell straddles a chunk
  // boundary, parser state (inQuotes + partial cell + partial row)
  // must carry across the call. This simulates that path by splitting
  // a small buffer at a deliberately awkward index.
  const full = 'a,b\n"line1\nline2\nline3",ok\nx,y\n';
  // Find an index that's INSIDE the quoted cell (between "line1" and
  // its closing quote) so the boundary is the worst case.
  const splitAt = full.indexOf('line2');
  assert.ok(splitAt > 0 && splitAt < full.length - 1, 'split index sanity');
  const chunkA = full.substring(0, splitAt);
  const chunkB = full.substring(splitAt);

  const state = CsvRenderer.initParserState();
  const a = CsvRenderer.parseChunk(chunkA, 0, state, ',', {
    baseOffset: 0, maxRows: 0, flush: false,
  });
  const b = CsvRenderer.parseChunk(chunkB, 0, state, ',', {
    baseOffset: 0, maxRows: 0, flush: true,
  });
  const rows = host([...a.rows, ...b.rows]);
  assert.deepEqual(rows, [
    ['a', 'b'],
    ['line1\nline2\nline3', 'ok'],
    ['x', 'y'],
  ]);
});

test('csv-parser: maxRows respects the cap and resumes on the next call', () => {
  // The streaming sync path passes maxRows=CHUNK_ROWS_FIRST to paint
  // quickly and then maxRows=CHUNK_ROWS_STREAM for subsequent chunks.
  // Two consecutive parseChunk calls with caps must produce the same
  // rows as a single uncapped call.
  const text = 'h\n1\n2\n3\n4\n5\n';
  const state = CsvRenderer.initParserState();
  const a = CsvRenderer.parseChunk(text, 0, state, ',', {
    baseOffset: 0, maxRows: 3, flush: false,
  });
  assert.equal(a.rows.length, 3);
  const b = CsvRenderer.parseChunk(text, a.endIdx, state, ',', {
    baseOffset: 0, maxRows: 0, flush: true,
  });
  const rows = host([...a.rows, ...b.rows]);
  assert.deepEqual(rows, [['h'], ['1'], ['2'], ['3'], ['4'], ['5']]);
});

// ── Row offsets ────────────────────────────────────────────────────────

test('csv-parser: rowOffsets span multi-line quoted cells', () => {
  // The grid viewer's click-to-focus engine uses rowOffsets to map a
  // grid row to a byte range in the original buffer. A multi-line
  // quoted cell's row offsets must span the WHOLE logical row,
  // including the embedded newlines.
  const text = 'h\n"line1\nline2",ok\nx,y\n';
  const state = CsvRenderer.initParserState();
  const result = CsvRenderer.parseChunk(text, 0, state, ',', {
    baseOffset: 0, maxRows: 0, flush: true,
  });
  // Header at offset 0..1 (the `\n` after `h`).
  assert.equal(result.rowOffsets[0].start, 0);
  assert.equal(result.rowOffsets[0].end, 1);
  // The multi-line body row starts at the `"` after the header `\n`
  // and ends at the `\n` AFTER `,ok` — spanning both physical newlines.
  const bodyStart = text.indexOf('"');
  const bodyEnd = text.indexOf('\n', text.indexOf('ok'));
  assert.equal(result.rowOffsets[1].start, bodyStart);
  assert.equal(result.rowOffsets[1].end,   bodyEnd);
});

// ── Delimiter sniffing ─────────────────────────────────────────────────

test('csv-parser: _delim ignores delimiters inside quoted cells', () => {
  // A header with `"a,b"` should not let the comma inside the quoted
  // cell vote toward `,` as the delimiter. With a tab present
  // outside any quotes, `\t` should win.
  const r = new CsvRenderer();
  const text = '"a,b,c"\thdr2\thdr3\n1\t2\t3\n';
  assert.equal(r._delim(text), '\t');
});

test('csv-parser: _delim keeps quote-awareness across newlines in the sample window', () => {
  // A header cell with an embedded newline used to break the line-only
  // sniff; the new sniff treats the whole quoted region as quoted
  // even when it contains a `\n`.
  const r = new CsvRenderer();
  const text = '"multi\nline\nheader",b,c\n1,2,3\n';
  // `,` is the only candidate that occurs unquoted (between `"..."` and
  // `b`, then between `b` and `c`).
  assert.equal(r._delim(text), ',');
});

// ── Width policy (renderer wrapper layer) ──────────────────────────────

test('csv-parser: _parse returns rowOffsets aligned to absolute buffer', () => {
  // _parse is the renderer wrapper that calls parseChunk with flush:true
  // — the offsets it returns must already be absolute in the original
  // text (they're handed straight to the grid viewer for click-to-focus).
  const r = new CsvRenderer();
  const text = 'h1,h2\nrow1a,row1b\nrow2a,row2b\n';
  const out = r._parse(text, ',', text.indexOf('\n') + 1);
  assert.equal(out.rows.length, 2);
  // First body row's offsets should bracket "row1a,row1b".
  const r1Start = text.indexOf('row1a');
  const r1End   = text.indexOf('\n', r1Start);
  assert.equal(out.rowOffsets[0].start, r1Start);
  assert.equal(out.rowOffsets[0].end,   r1End);
});
