'use strict';
// ════════════════════════════════════════════════════════════════════════════
// mmdb-reader.test.js — Hand-rolled MaxMind DB reader, exercised against
// a tiny hand-crafted fixture (`tests/fixtures/test-country.mmdb`, ~833
// bytes, 24-bit records, IPv4-only tree).
//
// The fixture is generated by `scripts/misc/build_test_mmdb.py`
// (one-time, output committed). It contains four canonical prefixes:
//   • 8.8.8.0/24    → United States / US
//   • 1.1.1.0/24    → Australia    / AU
//   • 193.0.0.0/24  → Netherlands  / NL
//   • 210.130.0.0/16→ Japan        / JP
//
// What this proves:
//   1. The metadata block parses cleanly: database_type, record_size
//      (24-bit), node_count, ip_version (4), build_epoch.
//   2. `lookupIPv4` walks the binary search tree to the right leaf
//      and decodes the GeoLite2-shape data record.
//   3. `formatRow` produces the country-only `<Country>/<ISO>` shape
//      with trailing-slash trim.
//   4. Off-tree IPs (no matching prefix) resolve to null without
//      throwing, no leak of partially-parsed data.
//   5. Bad input (non-string, malformed dotted-quad, IPv6) returns
//      null without throwing.
//   6. Provider-contract surface (`getFieldName`, `vintage`,
//      `providerKind`, `databaseType`) returns the expected values.
//
// Why the tiny fixture instead of a real GeoLite2 / DB-IP DB?
//   • CI must not depend on an 8 MB binary for a parser unit test.
//   • The minimal fixture exercises every code path in the reader
//     (metadata parse, tree walk, control-byte decode for utf-8 /
//     uint16 / uint32 / map, pointer-less data records). The 28-bit
//     record_size path and IPv4-in-IPv6 tree are exercised
//     end-to-end by `tests/e2e-fixtures/timeline-geoip.spec.ts`
//     against the bundled provider; the MMDB tree walk has the same
//     control-byte decoder.
//
// What this does NOT cover:
//   • The 28-bit / 32-bit record_size paths. The fixture uses 24-bit
//     because it's the smallest legal value and produces the shortest
//     fixture; the reader handles all three (`_readLeftRecord`).
//     Coverage of 28-bit paths can be added by extending the fixture
//     builder if a regression appears.
//   • The IPv6 tree-walk path (`_findIpv4Start` for ip_version=6).
//     Same reason as above; the v4-only fixture is sufficient for
//     parser correctness and the v6-prefix walk is just 96 left-only
//     descents through cached node 0 of an empty tree.
//   • The gzip-detection path (`MmdbReader.fromBlob` with a `.mmdb.gz`
//     blob) — would require a `Decompressor` shim under vm. The
//     uncompressed path is the dominant case; gzip handling is the
//     same `Decompressor.tryDecompress` everything else uses.
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { loadModules, REPO_ROOT } = require('../helpers/load-bundle.js');

const FIXTURE = path.join(REPO_ROOT, 'tests', 'fixtures', 'test-country.mmdb');

// Read the fixture once. If it's missing, fail loudly — unlike the
// optional DB-IP fixture this used to point at, the hand-crafted
// fixture is committed and CI must always have it. A missing fixture
// here means the file got deleted or the path moved; both are
// regressions.
const FIXTURE_BYTES = fs.readFileSync(FIXTURE);
const FIXTURE_AVAILABLE = true;

function loadReader() {
  // No special globals required — the module is self-contained beyond
  // the gzip path (which we don't exercise here). `Uint8Array` is
  // already in the default sandbox (see load-bundle.js::makeSandbox).
  const ctx = loadModules(['src/geoip/mmdb-reader.js'], {
    expose: ['MmdbReader', 'MmdbInvalidError'],
  });
  assert.ok(ctx.MmdbReader, 'MmdbReader should be exposed');
  assert.ok(ctx.MmdbInvalidError, 'MmdbInvalidError should be exposed');
  return ctx;
}

// Wrap host bytes in a sandbox-realm Uint8Array so the constructor's
// `bytes[i]` reads work. `vm.runInContext` shares the V8 heap, so a
// host Uint8Array with `.byteLength` works — but we pass through the
// `loadModules` exposed constructor explicitly to guarantee realm
// agreement on the typed-array prototype chain.
function realmBytes(ctx) {
  const SandboxU8 = ctx.Uint8Array || Uint8Array;
  const out = new SandboxU8(FIXTURE_BYTES.length);
  out.set(FIXTURE_BYTES);
  return out;
}

test('metadata parse — hand-crafted fixture decodes to expected shape', () => {
  const ctx = loadReader();
  const reader = new ctx.MmdbReader(realmBytes(ctx));

  // Fields stamped by `scripts/misc/build_test_mmdb.py`. A regression
  // in `_parseMetadata` would surface as a mismatch on any of these.
  assert.equal(reader.databaseType, 'Loupe-Test-Country');
  assert.equal(reader.ipVersion, 4);
  assert.equal(reader.providerKind, 'mmdb');
  assert.equal(reader.getFieldName(), 'geo');
  // node_count varies depending on the prefix coverage; lock to the
  // value the current builder produces. A change to this number means
  // the builder's tree shape changed — prompt to re-eyeball the fixture.
  assert.equal(reader.nodeCount, 78);
  // build_epoch 1761955200 = 2025-11-01 UTC (the builder's pinned
  // SOURCE_DATE_EPOCH fallback). Vintage label format pinned so a
  // Settings-dialog UI change surfaces here.
  assert.equal(reader.buildEpoch, 1_761_955_200);
  assert.match(reader.vintage, /^Loupe-Test-Country built 2025-11-\d{2}$/);
});

test('lookupIPv4 — every prefix in the fixture resolves to its country', () => {
  const ctx = loadReader();
  const reader = new ctx.MmdbReader(realmBytes(ctx));

  // 8.8.8.0/24 → United States / US
  const us = reader.lookupIPv4('8.8.8.8');
  assert.ok(us, '8.8.8.8 should resolve');
  assert.equal(us.iso, 'US');
  assert.equal(us.country, 'United States');

  // 1.1.1.0/24 → Australia / AU
  const au = reader.lookupIPv4('1.1.1.1');
  assert.ok(au, '1.1.1.1 should resolve');
  assert.equal(au.iso, 'AU');
  assert.equal(au.country, 'Australia');

  // 193.0.0.0/24 → Netherlands / NL
  const nl = reader.lookupIPv4('193.0.0.1');
  assert.ok(nl, '193.0.0.1 should resolve');
  assert.equal(nl.iso, 'NL');
  assert.equal(nl.country, 'Netherlands');

  // 210.130.0.0/16 → Japan / JP. Test multiple IPs within the /16
  // to prove the tree walk reaches the same leaf for every address
  // in the prefix.
  for (const ip of ['210.130.1.1', '210.130.255.254', '210.130.0.1']) {
    const jp = reader.lookupIPv4(ip);
    assert.ok(jp, `${ip} should resolve`);
    assert.equal(jp.iso, 'JP', `${ip} → expected JP, got ${jp.iso}`);
  }
});

test('lookupIPv4 — adjacent IPs in same allocation produce consistent records', () => {
  // Pin that the binary-search tree walks to the same leaf for IPs
  // that share a prefix — off-by-one bugs in `_findIpv4` would
  // surface here.
  const ctx = loadReader();
  const reader = new ctx.MmdbReader(realmBytes(ctx));

  const a = reader.lookupIPv4('8.8.8.7');
  const b = reader.lookupIPv4('8.8.8.8');
  const c = reader.lookupIPv4('8.8.8.9');
  assert.ok(a && b && c, 'all 3 sample IPs should resolve');
  assert.equal(a.iso, b.iso);
  assert.equal(b.iso, c.iso);
  assert.equal(b.iso, 'US');
});

test('lookupIPv4 — off-tree IPs return null', () => {
  const ctx = loadReader();
  const reader = new ctx.MmdbReader(realmBytes(ctx));

  // None of these match any /24 or /16 in the fixture. All MUST
  // return null without throwing — exercises the "branch points at
  // node_count" miss path in `_findIpv4`.
  for (const ip of [
    '10.0.0.1',
    '172.16.0.1',
    '192.168.1.1',
    '127.0.0.1',
    '169.254.1.1',
    '224.0.0.1',
    '8.8.7.1',          // close to 8.8.8.0/24 but in a sibling subtree
    '8.8.9.1',          // immediately after the 8.8.8.0/24 prefix
    '193.0.1.1',        // immediately after the 193.0.0.0/24 prefix
    '210.131.0.1',      // outside the 210.130.0.0/16 prefix
  ]) {
    assert.equal(
      reader.lookupIPv4(ip),
      null,
      `off-tree ${ip} should resolve to null`,
    );
  }
});

test('lookupIPv4 — bad input returns null without throwing', () => {
  const ctx = loadReader();
  const reader = new ctx.MmdbReader(realmBytes(ctx));

  for (const bad of [
    null,
    undefined,
    42,
    {},
    [],
    '',
    'not.an.ip',
    '256.1.1.1',
    '1.2.3',
    '1.2.3.4.5',
    '01.2.3.4',
    '::1',                  // IPv6 (not supported in v1)
    '2001:db8::1',
  ]) {
    assert.equal(
      reader.lookupIPv4(bad),
      null,
      `bad input ${JSON.stringify(bad)} should return null`,
    );
  }
});

test('formatRow — country-only shape with trailing-slash trim', () => {
  const ctx = loadReader();
  const reader = new ctx.MmdbReader(realmBytes(ctx));

  // Same formatter as bundled-geoip.js (the contract is shared).
  // Country DB never produces region/city, so the shape is always
  // `Country/ISO`.
  assert.equal(
    reader.formatRow({ country: 'Ireland', iso: 'IE' }),
    'Ireland/IE',
  );
  // City-DB shape (manually constructed — the country fixture won't
  // produce this, but the formatter contract is shared with the MMDB
  // reader's full implementation).
  assert.equal(
    reader.formatRow({ country: 'United States', iso: 'US', region: 'Louisiana', city: 'New Orleans' }),
    'United States/US/Louisiana/New Orleans',
  );
  // Internal empties dropped (region missing).
  assert.equal(
    reader.formatRow({ country: 'United States', iso: 'US', region: '', city: 'New York' }),
    'United States/US/New York',
  );
  assert.equal(reader.formatRow(null), '');
  assert.equal(reader.formatRow(undefined), '');
});

test('constructor — non-MMDB bytes throw MmdbInvalidError', () => {
  // Doesn't need the fixture — exercises the metadata-marker scan.
  const ctx = loadReader();
  // 1 KB of zeros: no metadata marker anywhere → InvalidError.
  const garbage = new (ctx.Uint8Array || Uint8Array)(1024);
  assert.throws(
    () => new ctx.MmdbReader(garbage),
    (err) => err instanceof ctx.MmdbInvalidError && /no metadata marker/.test(err.message),
  );
});
