'use strict';
// ════════════════════════════════════════════════════════════════════════════
// obfuscation-cmd-obfuscation-fuzz-regress-07c717a024bff004.test.js — fuzz regression reproducer.
//
// Auto-generated by `scripts/fuzz_promote.py` on 2026-05-04.
// Source crash:    dist/fuzz-crashes/obfuscation/cmd-obfuscation/07c717a024bff004/  (ephemeral)
// Source target:   tests/fuzz/targets/obfuscation/cmd-obfuscation.fuzz.js
// Stack hash:      07c717a024bff004
// Input variant:   original (842 bytes)
// Original throw:  Error: invariant: decode blowup — technique="CMD Env Var Substring (inline)" raw=13 deobf=682
//
// This test pins the absence of the regression. The fuzz finding's
// minimised input is base64-inlined below, fed through the SAME fuzz
// target (and therefore the SAME vm.Context, expose list, and
// invariants) that found the bug originally.  A future re-introduction
// of the bug will fail this test under `python make.py test-unit`,
// long before anyone re-runs the full fuzzer.
//
// Original stack (truncated to 11 lines):
// Error: invariant: decode blowup — technique="CMD Env Var Substring
// (inline)" raw=13 deobf=682
//     at Object.onIteration
// (/home/devuser/Projects/Loupe/tests/fuzz/targets/obfuscation/cmd-
// obfuscation.fuzz.js:114:15)
//     at fuzz
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/harness.js:224:17)
//     at main (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-
// runner.js:110:13)
//     at Object.<anonymous>
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-runner.js:158:1)
//     at Module._compile (node:internal/modules/cjs/loader:1521:14)
//     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
//     at Module.load (node:internal/modules/cjs/loader:1266:32)
//     at Module._load (node:internal/modules/cjs/loader:1091:12)
//     at Function.executeUserEntryPoint [as runMain]
// (node:internal/modules/run_main:164:12)
//     at node:internal/main/run_main_module:28:49
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// Load the fuzz target itself — single source of truth for which src/
// files to evaluate, which symbols to expose, and what invariants to
// assert per iteration.  No duplication.
const targetPath = path.resolve(
  __dirname, '..', 'fuzz', 'targets', 'obfuscation/cmd-obfuscation.fuzz.js',
);
const target = require(targetPath);

// Minimised crashing input, base64-encoded.
const INPUT_B64 =
  'JUI6fjMlP73akYyLn3QgZXQAAAAAAApbYwEAfAFJJ206CmVzAABzXnNeaP9zXnNeaHAlc15zXmgl'
  + 'ISEKc2V0IEM9ISVBJSElQiUgQckAAF9wcm90b19fAAAAF2dzXnNeM25zdHJ1Y3Rvci5wcm90b3R5'
  + 'cGVwZTAlJXZldCB2MD13YyUhISVCOn4zMCwzJSVDJSFjISEKc2V0IEI9ISVBJXNec15ocCVjb25z'
  + 'dHJ1Y3RvcnYxJSV2MiV3Y29uc15zXmhwZTElcAAAX19wcm90b19fACElQjp+MiwzJSUwLDMlJUMl'
  + 'IWMhISVCOn4yMCwzJSVDJSFjAGUAAAAhJSElQjp+MzAsMyUlQyUhYyEhJUI6fjIw1DMlJb3akYyL'
  + 'n4q8JSFjAGUAAAAhJSElQjp+MzAlJUMlQiFjLi4vLi4vamF6X3plciEhJUI6MCwzJSVDJSFjAGUA'
  + 'AAAhJSElQjp+MzAsMyUlQyUhYyEhJUI6fjIw1DMlJUMlbjAsQjp+MzAsMyUlQyUhYyEhJUI6fjIw'
  + 'LDMlJUMlMyUlQyUhYwBlAAAAISUhJUI6fjMwLDMlJUMlIWMhY29uc3RydWN0b3IucHJvdG90eXBl'
  + 'ISVCOn4yMNQzJSVDJW5zdGB1QyUhYwBlAAAAISUhJUI6fjMwJSVDJSFjISElQjowLDMlJUMlIWMA'
  + 'ZQAAACElISVCOn4zMCwzJSVDJSFjISElQjp+MjDUMyUlQyVuc3RgdUMlIWMAZQAAACElISVCOn4z'
  + 'MCUlQyUhYyEhJUJjb25zdHJ1Y3Rvcjp+MjAsMyUlQyVuc3RgdSFjISElQjp+MjAsb3IuJSVDJSFj'
  + 'ISF+MjAsMyUlQyVuc3Q9cil1Y3RvMCwzJSVDJSFjAGUAAAAhJSElQjp+MzAsMyUlQyUhYyEhJUI6'
  + 'fjIwMGMzMCwzJSEhJW5zdGB1QyUhYwBlAAAAISUhJUI6fjMwLDMlJUMlIWMhISVCOn4yMCwzJSVD'
  + 'JW5zdGB1IUJjISElQjp+MjAsb3IuJSVDJSFjISElQjp+NiUlQyWurq5ocCV2dF5hXgAAABdnc15j'
  + 'rq6urq6urq6urq6urq6uriFjAGUAAAAlISslQjp+MzAsMyUlQyUhYyEhJUI=';
const INPUT = Buffer.from(INPUT_B64, 'base64');

test('fuzz-regress[obfuscation/cmd-obfuscation/07c717a024bff004]: target runs cleanly on the historical crash buffer', async () => {
  // The target's `fuzz(buf)` already enforces the per-iteration budget
  // (DEFAULT_PER_ITER_BUDGET_MS=2500 in harness.js) and re-throws any
  // non-expected error with a stack-hash attached.  We simply assert
  // it doesn't throw.
  await assert.doesNotReject(target.fuzz(INPUT),
    `regression at hash 07c717a024bff004: ${INPUT.length} bytes still triggers a fuzz failure`);
});
