'use strict';
// ════════════════════════════════════════════════════════════════════════════
// obfuscation-cmd-obfuscation-fuzz-regress-3eccbcdc9620bc84.test.js — fuzz regression reproducer.
//
// Auto-generated by `scripts/fuzz_promote.py` on 2026-05-04.
// Source crash:    dist/fuzz-crashes/obfuscation/cmd-obfuscation/3eccbcdc9620bc84/  (ephemeral)
// Source target:   tests/fuzz/targets/obfuscation/cmd-obfuscation.fuzz.js
// Stack hash:      3eccbcdc9620bc84
// Input variant:   original (1375 bytes)
// Original throw:  Error: invariant: decode blowup — technique="CMD ClickFix Wrapper" raw=24 deobf=960
//
// This test pins the absence of the regression. The fuzz finding's
// minimised input is base64-inlined below, fed through the SAME fuzz
// target (and therefore the SAME vm.Context, expose list, and
// invariants) that found the bug originally.  A future re-introduction
// of the bug will fail this test under `python make.py test-unit`,
// long before anyone re-runs the full fuzzer.
//
// Original stack (truncated to 11 lines):
// Error: invariant: decode blowup — technique="CMD ClickFix Wrapper" raw=24
// deobf=960
//     at Object.onIteration
// (/home/devuser/Projects/Loupe/tests/fuzz/targets/obfuscation/cmd-
// obfuscation.fuzz.js:114:15)
//     at fuzz
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/harness.js:224:17)
//     at main (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-
// runner.js:110:13)
//     at Object.<anonymous>
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-runner.js:158:1)
//     at Module._compile (node:internal/modules/cjs/loader:1521:14)
//     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
//     at Module.load (node:internal/modules/cjs/loader:1266:32)
//     at Module._load (node:internal/modules/cjs/loader:1091:12)
//     at Function.executeUserEntryPoint [as runMain]
// (node:internal/modules/run_main:164:12)
//     at node:internal/main/run_main_module:28:49
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// Load the fuzz target itself — single source of truth for which src/
// files to evaluate, which symbols to expose, and what invariants to
// assert per iteration.  No duplication.
const targetPath = path.resolve(
  __dirname, '..', 'fuzz', 'targets', 'obfuscation/cmd-obfuscation.fuzz.js',
);
const target = require(targetPath);

// Minimised crashing input, base64-encoded.
const INPUT_B64 =
  'cwAA//////////8AF3h4eHhJU0VDeHh4eBd4eHh4SVNFQ3h4eHh4eHh4eHRhYWFhYWFjb25zdHJ1'
  + 'Y3ReUT1mb3IvZiAicz1uICgnc2hlbGwuZSllY2hvICIgICAgICBnIHogY2FwdGNoYScgL2ElUmFh'
  + 'YWFhYWFhYWFhYWFhYWFhYWFhY29uc3RydWN0b3IucHJvdG90eXBlYS1hYWFhYWN0YWFhYWFhYWFh'
  + 'bnN0cnVjdG9yYWFhYWFhYXh4eHg6eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHhhYWE9PT09PT09'
  + 'PT09PT09PT09YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhY29uc3RydWN0XlE9Zm9yL2YgInM9biAo'
  + 'JyVBJSElUiWlACcpIGRvICVYZXICp2UKc2V0IFI9c2hlbG9fJVJhYWFhYWFhYWFhYWFhYWFhYWFh'
  + 'YWFuc3RydWN0b3JhYWFhYWFhYUNNRCBFbnYgVmFyIChhcmd2MCljdG9yeHh4eHh4eHh4eHgxeHh4'
  + 'eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4YWFhYWFhYWFhYWFhYWFhYWFhY2FhYWFhYWFhYWFhYWEt'
  + 'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhY29uc3RydWN0b3JhYWFhYWFvYmplY2BhYWFh'
  + 'YWFhYWFuc3RydWN0b3JhYWFhYWFhYWFhYWFhYWFhYWFhYWNvbnN0cnVjdG9yeHhhYWFhYWFhYWFh'
  + 'YWFhYWFhYWFjYWFhYWFhY2FhYWFhYS1hYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFjb25zdHJ1'
  + 'Y3Rvcnh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4cHh4eGH/////////////YWFh'
  + 'YWFhYWFhY29uc3RyJXVjdG9yYWFhYWFhYWFhYWFhYWFhbnN0cnVjdG9yYWFhYWFhYWFhYWFhYWFh'
  + 'YWFhYWFjb25zdHJ1Y3Rvcnh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHp4eHh4eHh4eHh4'
  + 'eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHhhYWFhYWFhYWFhYWFhbnN0cnVjAAIAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0b3JhYWFh'
  + 'YWFhYWFhYWFhYWFhYWFhYWNvbnN0cnVjdG9yeHhhYWFhYWFhYWFhYWFhYWFhYWFjYWFhYWFhY2Fh'
  + 'YWFhYS1hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////'
  + '/////////////////////////////////////////////////////////wAAAAAAAAAnAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AABhYWFhYWFhYWFhYWFhYbS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0'
  + 'tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0YWFhYWFhYWFhYWFh'
  + 'Y29uc3RydWN0b3J4eHh4eHh4eHh4eHgKCiVDT00lCiVDT01TUEVDJU1TUEVDJUVDJU1TeHh4eHh4'
  + 'eHh4eHh4eHh4ULu82vUKeHh4eHh4eCVDT01TUEVDJQoKWFhQRUMlCgolQ09NU1BFQyUKClh4cHhY'
  + 'eHhhYWFhYQ==';
const INPUT = Buffer.from(INPUT_B64, 'base64');

test('fuzz-regress[obfuscation/cmd-obfuscation/3eccbcdc9620bc84]: target runs cleanly on the historical crash buffer', async () => {
  // The target's `fuzz(buf)` already enforces the per-iteration budget
  // (DEFAULT_PER_ITER_BUDGET_MS=2500 in harness.js) and re-throws any
  // non-expected error with a stack-hash attached.  We simply assert
  // it doesn't throw.
  await assert.doesNotReject(target.fuzz(INPUT),
    `regression at hash 3eccbcdc9620bc84: ${INPUT.length} bytes still triggers a fuzz failure`);
});
