'use strict';
// ════════════════════════════════════════════════════════════════════════════
// obfuscation-bash-obfuscation-fuzz-regress-780839c3269f6761.test.js — fuzz regression reproducer.
//
// Auto-generated by `scripts/fuzz_promote.py` on 2026-05-04.
// Source crash:    dist/fuzz-crashes/obfuscation/bash-obfuscation/780839c3269f6761/  (ephemeral)
// Source target:   tests/fuzz/targets/obfuscation/bash-obfuscation.fuzz.js
// Stack hash:      780839c3269f6761
// Input variant:   original (713 bytes)
// Original throw:  Error: invariant: decode blowup — technique="Bash Variable Expansion (single)" raw=6 deobf=285
//
// This test pins the absence of the regression. The fuzz finding's
// minimised input is base64-inlined below, fed through the SAME fuzz
// target (and therefore the SAME vm.Context, expose list, and
// invariants) that found the bug originally.  A future re-introduction
// of the bug will fail this test under `python make.py test-unit`,
// long before anyone re-runs the full fuzzer.
//
// Original stack (truncated to 11 lines):
// Error: invariant: decode blowup — technique="Bash Variable Expansion
// (single)" raw=6 deobf=285
//     at Object.onIteration
// (/home/devuser/Projects/Loupe/tests/fuzz/targets/obfuscation/bash-
// obfuscation.fuzz.js:72:15)
//     at fuzz
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/harness.js:224:17)
//     at main (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-
// runner.js:110:13)
//     at Object.<anonymous>
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-runner.js:158:1)
//     at Module._compile (node:internal/modules/cjs/loader:1521:14)
//     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
//     at Module.load (node:internal/modules/cjs/loader:1266:32)
//     at Module._load (node:internal/modules/cjs/loader:1091:12)
//     at Function.executeUserEntryPoint [as runMain]
// (node:internal/modules/run_main:164:12)
//     at node:internal/main/run_main_module:28:49
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// Load the fuzz target itself — single source of truth for which src/
// files to evaluate, which symbols to expose, and what invariants to
// assert per iteration.  No duplication.
const targetPath = path.resolve(
  __dirname, '..', 'fuzz', 'targets', 'obfuscation/bash-obfuscation.fuzz.js',
);
const target = require(targetPath);

// Minimised crashing input, base64-encoded.
const INPUT_B64 =
  'Uz0nc2ggL3RtcC9wcHJvdG90eXBlbGBkbyR7UzowOjF9JDIxAAB7SkQpRUY6MH0ke1M6MjoxfTk5'
  + 'OTk5OTk5OTk5OTk5OWYBAAAAYmFzZTY0IC1kIDw8PCAiZDIvaHZZVzFwInwgc2gocHJpbnRmJDox'
  + 'fSR7SkQpRUY6hH0kezk5OTlQPWYBAAAAYmFzZTY0IC1kIDw8PCAiZDIvaHZZVzFwInwgc2gocHJp'
  + 'InwgcHJvdG90eXBlPWYBAAAAYmFzZTY0IC1kIDw8PCAiZDIvaHZZVzFwInwgc2gocHJhc2U2NCA8'
  + 'PDwgImQxaHZZcHxXIiAxc2gocHJmIAAAYmFzZTY0IC1kIDw8PCAiZDIvaFd2MVlwInwgc2gocHJp'
  + 'bnRmICdceCB9Nv89c3JobnR1NyAkJCOhcwAnJyBzACQnADE6AAAAYmFzZTY0IC1kIDw8PCAiZDIv'
  + 'aHZZVzFwInwgc2gocHJpbnRmICdceCB9Nn0kOkUxKX1KRCV7RjqEfSR7UzoyOjF9OTk5OTk5OTk5'
  + 'OTk5OVA9ZgEAAABiYXNlNjQgLWQgPDw8ICJkMi9odllXMXAifCBzaChwcmludGYgJ1x4IH02/z1z'
  + 'MXAifCBwcm90b3R5cGU9ZgEAAHtTOjEyMX1yJHtTOjF9IHwke1M6MTMxfXIke1M6MX0gfCBiOlMk'
  + 'MX0kU3s6MToxfXIke1M6MX06MP////97UzoxOjF9ciR7UzoxfQBiYXNlNjQgLWQgPDw8ICJkMi9o'
  + 'dllXMXAifCBzaChwcmludGYgJ1x4ICAnXHggfTb/PXMxcCJ8IHByb3RvdHlwZT1mAQAAAGJhc2U2'
  + 'NCAtZCA8PDwgImQyL2h2WVcxcCJ8IHNoKHByaW50ZiAnXHggfTb/PXNyaG50dScgJCOhcwAnJyAA'
  + 'ACQnABBiYXNlNjQgLWQgPDxAPCAiZDFodllXMXA=';
const INPUT = Buffer.from(INPUT_B64, 'base64');

test('fuzz-regress[obfuscation/bash-obfuscation/780839c3269f6761]: target runs cleanly on the historical crash buffer', async () => {
  // The target's `fuzz(buf)` already enforces the per-iteration budget
  // (DEFAULT_PER_ITER_BUDGET_MS=2500 in harness.js) and re-throws any
  // non-expected error with a stack-hash attached.  We simply assert
  // it doesn't throw.
  await assert.doesNotReject(target.fuzz(INPUT),
    `regression at hash 780839c3269f6761: ${INPUT.length} bytes still triggers a fuzz failure`);
});
