'use strict';
// ════════════════════════════════════════════════════════════════════════════
// obfuscation-reassembly-fuzz-regress-a7b7de6aa63cf197.test.js — fuzz regression reproducer.
//
// Auto-generated by `scripts/fuzz_promote.py` on 2026-05-04.
// Source crash:    dist/fuzz-crashes/obfuscation/reassembly/a7b7de6aa63cf197/  (ephemeral)
// Source target:   tests/fuzz/targets/obfuscation/reassembly.fuzz.js
// Stack hash:      a7b7de6aa63cf197
// Input variant:   original (153 bytes)
// Original throw:  Error: invariant: mapReconToSource(89) returned 0, expected 105
//
// This test pins the absence of the regression. The fuzz finding's
// minimised input is base64-inlined below, fed through the SAME fuzz
// target (and therefore the SAME vm.Context, expose list, and
// invariants) that found the bug originally.  A future re-introduction
// of the bug will fail this test under `python make.py test-unit`,
// long before anyone re-runs the full fuzzer.
//
// Original stack (truncated to 6 lines):
// Error: invariant: mapReconToSource(89) returned 0, expected 105
//     at validateMapReconToSource (/home/devuser/Projects/Loupe/tests/fuzz/ta
// rgets/obfuscation/reassembly.fuzz.js:221:13)
//     at Object.onIteration (/home/devuser/Projects/Loupe/tests/fuzz/targets/
// obfuscation/reassembly.fuzz.js:366:7)
//     at process.processTicksAndRejections
// (node:internal/process/task_queues:95:5)
//     at async fuzz
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/harness.js:224:7)
//     at async main (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-
// runner.js:110:7)
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// Load the fuzz target itself — single source of truth for which src/
// files to evaluate, which symbols to expose, and what invariants to
// assert per iteration.  No duplication.
const targetPath = path.resolve(
  __dirname, '..', 'fuzz', 'targets', 'obfuscation/reassembly.fuzz.js',
);
const target = require(targetPath);

// Minimised crashing input, base64-encoded.
const INPUT_B64 =
  'Zm9yIC9mICVYIGluICgnYUhSMGNITTZMeTlqWkc0dGRYQmtZWFJsTG0xaGJIZGhjbVV0YUc5emRD'
  + 'MDBNaTVsZUdGdGNHeGxMM0F2WVM1bGVHVT0nKSBkbyBjYWxsICVYDQpzZXQgVjE9cF5vXndeZV5y'
  + 'XnNeaF5lXmxebA0Kc2V0IFYyPU1UazRMalV4TGpFd01DNHhOemM9';
const INPUT = Buffer.from(INPUT_B64, 'base64');

test('fuzz-regress[obfuscation/reassembly/a7b7de6aa63cf197]: target runs cleanly on the historical crash buffer', async () => {
  // The target's `fuzz(buf)` already enforces the per-iteration budget
  // (DEFAULT_PER_ITER_BUDGET_MS=2500 in harness.js) and re-throws any
  // non-expected error with a stack-hash attached.  We simply assert
  // it doesn't throw.
  await assert.doesNotReject(target.fuzz(INPUT),
    `regression at hash a7b7de6aa63cf197: ${INPUT.length} bytes still triggers a fuzz failure`);
});
