'use strict';
// ════════════════════════════════════════════════════════════════════════════
// obfuscation-cmd-obfuscation-fuzz-regress-3b5994363eb12ea0.test.js — fuzz regression reproducer.
//
// Auto-generated by `scripts/fuzz_promote.py` on 2026-05-04.
// Source crash:    dist/fuzz-crashes/obfuscation/cmd-obfuscation/3b5994363eb12ea0/  (ephemeral)
// Source target:   tests/fuzz/targets/obfuscation/cmd-obfuscation.fuzz.js
// Stack hash:      3b5994363eb12ea0
// Input variant:   minimised (363 bytes)
// Original throw:  Error: invariant: decode blowup — technique="CMD Delayed-Expansion Indirection" raw=5 deobf=507
//
// NOTE: Jazzer found raw=5 !cmd! → deobf=507 blowup (107× amp) in single-bang delayed-expansion branch; branch 2 at cmd-obfuscation.js:414 was missing the 32×-raw / 8 KiB cap that branch 1 (line 364) already had. Regression twin of pain-point 25f2e66.
//
// This test pins the absence of the regression. The fuzz finding's
// minimised input is base64-inlined below, fed through the SAME fuzz
// target (and therefore the SAME vm.Context, expose list, and
// invariants) that found the bug originally.  A future re-introduction
// of the bug will fail this test under `python make.py test-unit`,
// long before anyone re-runs the full fuzzer.
//
// Original stack (truncated to 11 lines):
// Error: invariant: decode blowup — technique="CMD Delayed-Expansion
// Indirection" raw=5 deobf=507
//     at Object.onIteration
// (/home/devuser/Projects/Loupe/tests/fuzz/targets/obfuscation/cmd-
// obfuscation.fuzz.js:111:15)
//     at fuzz
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/harness.js:224:17)
//     at main (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-
// runner.js:110:13)
//     at Object.<anonymous>
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-runner.js:158:1)
//     at Module._compile (node:internal/modules/cjs/loader:1521:14)
//     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
//     at Module.load (node:internal/modules/cjs/loader:1266:32)
//     at Module._load (node:internal/modules/cjs/loader:1091:12)
//     at Function.executeUserEntryPoint [as runMain]
// (node:internal/modules/run_main:164:12)
//     at node:internal/main/run_main_module:28:49
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// Load the fuzz target itself — single source of truth for which src/
// files to evaluate, which symbols to expose, and what invariants to
// assert per iteration.  No duplication.
const targetPath = path.resolve(
  __dirname, '..', 'fuzz', 'targets', 'obfuscation/cmd-obfuscation.fuzz.js',
);
const target = require(targetPath);

// Minimised crashing input, base64-encoded.
const INPUT_B64 =
  'IGVuYWJsZWRlbGF5ZWRleHBhbnNpb24gIWNtZCEgIHNldCBjbWQ9aGcgdjB0b19fJSFNU1BFQ0Il'
  + 'IU1TUEVDOn4yISVOISElQiUhTVNQRUM6fjIyMSElToHP0zMlJUNPISVCJSFNU1BFQ0IlIU1TUEVD'
  + 'On4yISVOISElQiUhTVNQRUM6fjIxIUFCJSFNYyAhJWElISElQiUhTVNQRVBFQzp+MjEhJU6Bz9Mz'
  + 'JSFNU1BFQzp+MjEhJSFNU1BFQzp+MjEhJU6Bz9MzJSVDTyElQiUhTSFNU1BFQzp+MjEhJU6Bz9Mz'
  + 'JSVDTyElQiUhYyAhJUElISElQiUhTW5zXnNeaHBlMSVwAAAAMD03Y2ZTUEVDOn4yMSElToH/////'
  + '////AiVCJSFNU1BFQ0IlIU1TUEVDOn4yISVOISElQiUhTVNQRUM6fjIxIUFCJSFNYyAhJWFGJSEh'
  + 'YyVCJSFNMiElToHP0zMlJUNPTWgg';
const INPUT = Buffer.from(INPUT_B64, 'base64');

test('fuzz-regress[obfuscation/cmd-obfuscation/3b5994363eb12ea0]: target runs cleanly on the historical crash buffer', async () => {
  // The target's `fuzz(buf)` already enforces the per-iteration budget
  // (DEFAULT_PER_ITER_BUDGET_MS=2500 in harness.js) and re-throws any
  // non-expected error with a stack-hash attached.  We simply assert
  // it doesn't throw.
  await assert.doesNotReject(target.fuzz(INPUT),
    `regression at hash 3b5994363eb12ea0: ${INPUT.length} bytes still triggers a fuzz failure`);
});
