'use strict';
// ════════════════════════════════════════════════════════════════════════════
// obfuscation-bash-obfuscation-fuzz-regress-dafcdf82fa0849ca.test.js — fuzz regression reproducer.
//
// Auto-generated by `scripts/fuzz_promote.py` on 2026-05-04.
// Source crash:    dist/fuzz-crashes/obfuscation/bash-obfuscation/dafcdf82fa0849ca/  (ephemeral)
// Source target:   tests/fuzz/targets/obfuscation/bash-obfuscation.fuzz.js
// Stack hash:      dafcdf82fa0849ca
// Input variant:   original (1777 bytes)
// Original throw:  Error: invariant: decode blowup — technique="Bash Variable Concatenation (partial)" raw=6 deobf=228
//
// This test pins the absence of the regression. The fuzz finding's
// minimised input is base64-inlined below, fed through the SAME fuzz
// target (and therefore the SAME vm.Context, expose list, and
// invariants) that found the bug originally.  A future re-introduction
// of the bug will fail this test under `python make.py test-unit`,
// long before anyone re-runs the full fuzzer.
//
// Original stack (truncated to 11 lines):
// Error: invariant: decode blowup — technique="Bash Variable Concatenation
// (partial)" raw=6 deobf=228
//     at Object.onIteration
// (/home/devuser/Projects/Loupe/tests/fuzz/targets/obfuscation/bash-
// obfuscation.fuzz.js:72:15)
//     at fuzz
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/harness.js:224:17)
//     at main (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-
// runner.js:110:13)
//     at Object.<anonymous>
// (/home/devuser/Projects/Loupe/tests/fuzz/helpers/replay-runner.js:158:1)
//     at Module._compile (node:internal/modules/cjs/loader:1521:14)
//     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
//     at Module.load (node:internal/modules/cjs/loader:1266:32)
//     at Module._load (node:internal/modules/cjs/loader:1091:12)
//     at Function.executeUserEntryPoint [as runMain]
// (node:internal/modules/run_main:164:12)
//     at node:internal/main/run_main_module:28:49
// ════════════════════════════════════════════════════════════════════════════

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

// Load the fuzz target itself — single source of truth for which src/
// files to evaluate, which symbols to expose, and what invariants to
// assert per iteration.  No duplication.
const targetPath = path.resolve(
  __dirname, '..', 'fuzz', 'targets', 'obfuscation/bash-obfuscation.fuzz.js',
);
const target = require(targetPath);

// Minimised crashing input, base64-encoded.
const INPUT_B64 =
  'Uz0nYT1rCmI9bW0KYWE9Cj0KYz0nYyl0cHQnCmUvdj1pClM9IngibyRhJGIkYz1pCiRrCjZpClM9'
  + 'IngibyRhJGIkYz1pCiQnCmUvdj1pClM9IngibyRhPWsKNgAAAAAAAAAKCmUvdj1pClM9IngibyRh'
  + 'JGIkYz1pCiQAAABhPWsKNmkKUz0ieCJvJGEkYiRjPWkKJGE9awo2AAAAAAAAAAoKZS92PWkKUz0i'
  + 'eCJvJGE9CmM9J2MpdHB0JwplL3Y9aQpTPSJ4Im8kYSRiJGM9aQokaQpTPSJ4Im8kYSRiJGM9aQok'
  + 'AAAAYT1rCjJpClM9IngibyRhJGIkYz1pCiQnCmUvdj1pClM9IngibyRhJGIkYz1pCiRhPWsKNgAA'
  + 'AAAAAAAKCmUvdj1pClM9IngibyRhJGIkYz1pCiQAAABhPWsKNmkKUz0ieCJvJGEkYiRjPWkKJGFv'
  + 'JGEkYiRjPWkKJGsKNmkKUz0ieCJvJGEkYiRjPQoKZS92PWkKUz0ieCJvJGEkYiRjPWkKJAAAAGE9'
  + 'awo2aQpTPSJ4Im8kYSRiJGM9aQokYT1rCjYAAAAAAAAACgplL3YpaQpTPSJ4Im8kYT0KYz0nYyl0'
  + 'cHQnCmUvdj1pClM9IngibyRhJGIkYz1pCiRpClM9IngibyRhJGIkYz1pCiQAAABhPWsKNmkKUz0i'
  + 'eCJvJGEkYiRjPWkKJCcKZS92PWkKY29uc3RydWN0b3JTPSJ4Im8kYSRiJGM9aQokYT1rCjYAAAAA'
  + 'AAAACgplL3Y9aQpTPSJ4Im8kYT1iJGM9aQokAAAAYT1rCjZpYgpTPSJ4Im8kYSRiJGM9aQokYT1r'
  + 'CjYAAAAAAAAACgplL3Y9aQpTPSJ4Im8kYT0KYz0nYyl0cHQnCmUvdj1pClM9IngiYT1rCjYAAAAA'
  + 'AAAACgAKZS92PWkKUz0ieCJvJGE9CmM9J2MpdFg9WHdob2FtaVggLGZvbyAke1gvL1gvfW8ke1gv'
  + 'L1gvfW9hLy/19fX1czsgICRvbyAke1gvL1gvfQEAb29vICR7WC8vWC99byR7WC8vWC99b2FtcFx4'
  + 'MWVccFggb21hIGZvbyAke1hYLy9YL31vJHtYLy9YL31vYW1YIGhvYXByb3RvdHlwZW1pWCBmb28g'
  + 'JHtYLy9YL31vb28gJHtYLy9YL31vJHtYLy9YL30vWC99b2FtcFx4MWVccFggb21hIGZvbyAke1gv'
  + 'L1gvfW9vbyAke1gvL1gvfW9hbWknXDZcMDcyXFUwJAAAAAAAAAAwNmNvbv9yXFUwMDZjJ29vICR7'
  + 'WC8vWC99b29vICR7WC8vWC99byR7WC8vWC99b2FtWCBob2FtaVggZm9vICR7WC8vWC99b29vICR7'
  + 'WC8vWC99byR7WC8vWC99cHJvdG90eXBlbWlYIHtYbWlYLy9YL31vb28gJHtYLy9YL31vYW1pJ1w2'
  + 'XDA3MlxVMCQA//8AAAAAMDZjb27/clxVMDA2YydvbyAke1gvL1gvfW9vbyAke1gvL1gvfW8ke1gv'
  + 'L1gvfW9hbVggaG9hcHJvdG90eXBlbWlYIGZvbyAke1gvL1gvfW9vbyAke1gvL1gvfW8ke1gvL1gv'
  + 'fS9YL31vYW1wXHgxZVxwWCBvbWEgZm9vICR7WC8vWC99b29vICR7WC8vWC99b2FtaSdcNlwwNzJc'
  + 'VTAkAAAAAAAAADA2Y29uNmMnb28gJHtYLy9YL31vb28gJHtYLy9YL31vJHtYLy9YL31vYW1YIGhv'
  + 'YW1pWCBmb28gJHtYLy9YL31vb28gJHtYLy9YL31vJHtYLy9YL31vYW1pWCBob2FtaVgge1htaVgg'
  + 'aG9hbWl9b29vICR7WHR5cGVvbyAke1gvL1gvfQEAb29vICR7WC8vWC9YL31vJHtjb25zdHJ1Y3Rv'
  + 'clgvL1gvfW8gLGZvbyAke1gvL1gvfW8ke1gvL1gvfW9hLy/19fX1czsgICQnXDVcX19wcm90b19f'
  + 'MThcVTAwNmNvbv9yXFUwMDZjJ29vICR7WC8vWC99b29vICR7WHB0JwplL3Y9Ly9YL31vJHtYLy9Y'
  + 'L31vYW1YIGhvYW1pWCBmb28gJHtYLy9YL30Hb28gJHtYLy9YL31vJHtYLy9YL31vYW1pWCBob2Ft'
  + 'aVgge1htaWkKUz0ieCJhPWsKNgAAAAAAAAAKCmUvdj1pAQA9IngibyRhJGIkYz1pCiQAAABhPWsK'
  + 'NmkKUz0ieCJvJGEkYiRjPWlpCiQnCmVvdG9fX2kKUz0ieCJvJGEkYiRjPWkKJAAAAGE9awo2aQpT'
  + 'PSJ4Im8kYSRiJGM9aQokYT1rCjYAAAAAAAAACgplL3Y9aQpTPSJ4Im8kYT0KWCBob2Fta31vb28k'
  + 'e2NvbnNjdD0ncg==';
const INPUT = Buffer.from(INPUT_B64, 'base64');

test('fuzz-regress[obfuscation/bash-obfuscation/dafcdf82fa0849ca]: target runs cleanly on the historical crash buffer', async () => {
  // The target's `fuzz(buf)` already enforces the per-iteration budget
  // (DEFAULT_PER_ITER_BUDGET_MS=2500 in harness.js) and re-throws any
  // non-expected error with a stack-hash attached.  We simply assert
  // it doesn't throw.
  await assert.doesNotReject(target.fuzz(INPUT),
    `regression at hash dafcdf82fa0849ca: ${INPUT.length} bytes still triggers a fuzz failure`);
});
